version: "3.9"
name: "error_handler_database"
services:
  postgres_db:
    image: postgres:latest
    container_name: diploma_postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: error_handler_db
    volumes:
      - diploma_postgres_data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      common_network:


  pgadmin:
    container_name: pgadmindiploma
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: rozhk@diploma.com
      PGADMIN_DEFAULT_PASSWORD: rozhk
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      common_network:

  
  api:
    container_name: error_handler_api
    build: ../api/
    restart: always
    ports:
      - "8080:8080"
    networks:
      common_network:
    depends_on:
      - postgres_db


  web_client:
    container_name: error_handler_web_client
    build: ../client/
    restart: always
    ports:
      - "3000:3000"
    networks:
      common_network:


networks:
  common_network:


volumes:
  diploma_postgres_data:
  pgadmin-data: